export const GET_ITEM = 'GET_ITEM';
export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESSES = 'GET_ADDRESSES';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_CASETYPE = 'GET_CASETYPE';
export const GET_CASETYPES = 'GET_CASETYPES';
export const ADD_CASETYPE = 'ADD_CASETYPE';
export const UPDATE_CASETYPE = 'UPDATE_CASETYPE';
export const DELETE_CASETYPE = 'DELETE_CASETYPE';

export const GET_CITY = 'GET_CITY';
export const GET_CITIES = 'GET_CITIES';
export const ADD_CITY = 'ADD_CITY';
export const UPDATE_CITY = 'UPDATE_CITY';
export const DELETE_CITY = 'DELETE_CITY';

export const GET_COLOR = 'GET_COLOR';
export const GET_COLORS = 'GET_COLORS';
export const ADD_COLOR = 'ADD_COLOR';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const DELETE_COLOR = 'DELETE_COLOR';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANIES = 'GET_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';

export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';

export const GET_CUSTOMER = 'GET_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const GET_DEALER = 'GET_DEALER';
export const GET_DEALERS = 'GET_DEALERS';
export const ADD_DEALER = 'ADD_DEALER';
export const UPDATE_DEALER = 'UPDATE_DEALER';
export const DELETE_DEALER = 'DELETE_DEALER';

export const GET_DISTRICT = 'GET_DISTRICT';
export const GET_DISTRICTS = 'GET_DISTRICTS';
export const ADD_DISTRICT = 'ADD_DISTRICT';
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT';
export const DELETE_DISTRICT = 'DELETE_DISTRICT';

export const GET_DRIVERLICENCE = 'GET_DRIVERLICENCE';
export const GET_DRIVERLICENCES = 'GET_DRIVERLICENCES';
export const ADD_DRIVERLICENCE = 'ADD_DRIVERLICENCE';
export const UPDATE_DRIVERLICENCE = 'UPDATE_DRIVERLICENCE';
export const DELETE_DRIVERLICENCE = 'DELETE_DRIVERLICENCE';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export const GET_FUELTYPE = 'GET_FUELTYPE';
export const GET_FUELTYPES = 'GET_FUELTYPES';
export const ADD_FUELTYPE = 'ADD_FUELTYPE';
export const UPDATE_FUELTYPE = 'UPDATE_FUELTYPE';
export const DELETE_FUELTYPE = 'DELETE_FUELTYPE';

export const GET_GEARTYPE = 'GET_GEARTYPE';
export const GET_GEARTYPES = 'GET_GEARTYPES';
export const ADD_GEARTYPE = 'ADD_GEARTYPE';
export const UPDATE_GEARTYPE = 'UPDATE_GEARTYPE';
export const DELETE_GEARTYPE = 'DELETE_GEARTYPE';

export const GET_INVOICE = 'GET_INVOICE';
export const GET_INVOICES = 'GET_INVOICES';
export const ADD_INVOICE = 'ADD_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

export const GET_ORDERITEM = 'GET_ORDERITEM';
export const GET_ORDERITEMS = 'GET_ORDERITEMS';
export const ADD_ORDERITEM = 'ADD_ORDERITEM';
export const UPDATE_ORDERITEM = 'UPDATE_ORDERITEM';
export const DELETE_ORDERITEM = 'DELETE_ORDERITEM';

export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';

export const GET_PAYMENTTYPE = 'GET_PAYMENTTYPE';
export const GET_PAYMENTTYPES = 'GET_PAYMENTTYPES';
export const ADD_PAYMENTTYPE = 'ADD_PAYMENTTYPE';
export const UPDATE_PAYMENTTYPE = 'UPDATE_PAYMENTTYPE';
export const DELETE_PAYMENTTYPE = 'DELETE_PAYMENTTYPE';

export const GET_TOWN = 'GET_TOWN';
export const GET_TOWNS = 'GET_TOWNS';
export const ADD_TOWN = 'ADD_TOWN';
export const UPDATE_TOWN = 'UPDATE_TOWN';
export const DELETE_TOWN = 'DELETE_TOWN';

export const GET_VEHICLEBRAND = 'GET_VEHICLEBRAND';
export const GET_VEHICLEBRANDS = 'GET_VEHICLEBRANDS';
export const ADD_VEHICLEBRAND = 'ADD_VEHICLEBRAND';
export const UPDATE_VEHICLEBRAND = 'UPDATE_VEHICLEBRAND';
export const DELETE_VEHICLEBRAND = 'DELETE_VEHICLEBRAND';

export const GET_VEHICLECATEGORY = 'GET_VEHICLECATEGORY';
export const GET_VEHICLECATEGORIES = 'GET_VEHICLECATEGORIES';
export const ADD_VEHICLECATEGORY = 'ADD_VEHICLECATEGORY';
export const UPDATE_VEHICLECATEGORY = 'UPDATE_VEHICLECATEGORY';
export const DELETE_VEHICLECATEGORY = 'DELETE_VEHICLECATEGORY';

export const GET_VEHICLE = 'GET_VEHICLE';
export const GET_VEHICLES = 'GET_VEHICLES';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';

export const GET_VEHICLEMODEL = 'GET_VEHICLEMODEL';
export const GET_VEHICLEMODELS = 'GET_VEHICLEMODELS';
export const ADD_VEHICLEMODEL = 'ADD_VEHICLEMODEL';
export const UPDATE_VEHICLEMODEL = 'UPDATE_VEHICLEMODEL';
export const DELETE_VEHICLEMODEL = 'DELETE_VEHICLEMODEL';

export const OPEN_NAVBAR = 'OPEN_NAVBAR';
export const OPEN_FOOTER = 'OPEN_FOOTER';
export const CLOSE_NAVBAR = 'CLOSE_NAVBAR';
export const CLOSE_FOOTER = 'CLOSE_FOOTER';
